development:
  adapter: postgresql
  encoding: unicode
  database: data_developers_do_development
  username: "data_developers_do_user"
  password: "data_developers_do_pass"
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: data_developers_do_test
  pool: 5
  username: data_developers_do
  password:
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PG_DB'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>